/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ventanas;

/**
 *
 * @author raulch
 */
import java.sql.*;
import Conector.Conexion;


public class panelInfoLibro extends javax.swing.JPanel {

    private String codigo_barras;
    private String titulo_libro;
    private String nombre_autor;
    private String editorial;
    private String isbn;
    private String existencia;
    private String precio;
    Conexion con = new Conexion();
    Connection cn = con.conectar(); 
    
    
    public panelInfoLibro() {
        initComponents();
        codigo_barras = "";
        titulo_libro = "";
        nombre_autor = "";
        editorial = "";
        isbn = "";
        existencia = "";
        precio = "";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblAutor = new javax.swing.JLabel();
        lblEditorial = new javax.swing.JLabel();
        lblIsbn = new javax.swing.JLabel();
        lblExistencia = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Información del libro"));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        lblTitulo.setText("Titulo: ");

        lblAutor.setText("Autor: ");

        lblEditorial.setText("Editorial:");

        lblIsbn.setText("ISBN:");

        lblExistencia.setText("Existencia:");

        lblPrecio.setText("Precio:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo)
                    .addComponent(lblAutor)
                    .addComponent(lblEditorial)
                    .addComponent(lblIsbn)
                    .addComponent(lblExistencia)
                    .addComponent(lblPrecio))
                .addContainerGap(214, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAutor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEditorial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblIsbn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblExistencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPrecio)
                .addContainerGap(51, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    public void setCodigoBarras(String cb){
        codigo_barras = cb;
    }
    
    public void actualizaDatos(){
        String consulta = "SELECT * FROM libro WHERE codigoBarras=?";
        String idEditorial;
        String idAutor;
        try {
            PreparedStatement ps = cn.prepareStatement(consulta);
            ps.setString(1, codigo_barras);
            ResultSet rs = ps.executeQuery();
            if(rs.next()){
                titulo_libro = rs.getString(4);
                isbn = rs.getString(3);
                existencia = rs.getString(2);
                precio = rs.getString(5);
                idEditorial = rs.getString(7);
                
                consulta = "SELECT * FROM editorial WHERE idEditorial=?";
                ps = cn.prepareStatement(consulta);
                ps.setString(1, idEditorial);
                rs = ps.executeQuery();
                rs.next();
                editorial = rs.getString(2);
                
                consulta = "SELECT * FROM escribir WHERE codigoBarras=?";
                ps = cn.prepareStatement(consulta);
                ps.setString(1, codigo_barras);
                rs = ps.executeQuery();
                rs.next();
                idAutor = rs.getString(2);
                
                consulta = "SELECT * FROM autor WHERE idAutor=?";
                ps = cn.prepareStatement(consulta);
                ps.setString(1, idAutor);
                rs = ps.executeQuery();
                rs.next();
                nombre_autor = rs.getString(2);
                
                
                lblTitulo.setText("Titulo: "+titulo_libro);
                lblAutor.setText("Autor: "+nombre_autor);
                lblEditorial.setText("Editorial: "+editorial);
                lblIsbn.setText("ISBN: "+isbn);
                lblExistencia.setText("Existencia: "+existencia);
                lblPrecio.setText("Precio: "+precio);
                
                
            }
        }  catch (SQLException e) {
            System.out.println("error al conectar con la bd "+e );
        }
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAutor;
    private javax.swing.JLabel lblEditorial;
    private javax.swing.JLabel lblExistencia;
    private javax.swing.JLabel lblIsbn;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
