/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Ventanas;

/**
 *
 * @author Zaidc
 */
public class VentanaGraficas extends javax.swing.JDialog {

    /**
     * Creates new form ventanaGraficas
     */
    public VentanaGraficas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnLibrosVendidos = new javax.swing.JButton();
        btnLibrosEditorial = new javax.swing.JButton();
        btnLibrosPAutor = new javax.swing.JButton();
        btnTipoEmpleados = new javax.swing.JButton();
        panelGraficas = new Modelo.graficasBDD();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(213, 213, 243));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Gráficas");

        btnLibrosVendidos.setBackground(new java.awt.Color(153, 153, 153));
        btnLibrosVendidos.setText("Libros más vendidos");
        btnLibrosVendidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLibrosVendidosActionPerformed(evt);
            }
        });

        btnLibrosEditorial.setBackground(new java.awt.Color(153, 153, 153));
        btnLibrosEditorial.setText("Libros por editorial");
        btnLibrosEditorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLibrosEditorialActionPerformed(evt);
            }
        });

        btnLibrosPAutor.setBackground(new java.awt.Color(153, 153, 153));
        btnLibrosPAutor.setText("Cantidad de libros p/ Autor");
        btnLibrosPAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLibrosPAutorActionPerformed(evt);
            }
        });

        btnTipoEmpleados.setBackground(new java.awt.Color(153, 153, 153));
        btnTipoEmpleados.setText("Tipos de empleados");
        btnTipoEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTipoEmpleadosActionPerformed(evt);
            }
        });

        panelGraficas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnLibrosEditorial, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLibrosVendidos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLibrosPAutor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTipoEmpleados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(panelGraficas, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(btnLibrosVendidos)
                .addGap(18, 18, 18)
                .addComponent(btnLibrosEditorial)
                .addGap(18, 18, 18)
                .addComponent(btnLibrosPAutor)
                .addGap(18, 18, 18)
                .addComponent(btnTipoEmpleados)
                .addGap(28, 28, 28)
                .addComponent(panelGraficas, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLibrosVendidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLibrosVendidosActionPerformed
       panelGraficas.fillData("incluir", 2);
       panelGraficas.fillTit("libro", 1, 4);
       panelGraficas.iniGraficaPastel("Los mas vendidos");
    }//GEN-LAST:event_btnLibrosVendidosActionPerformed

    private void btnLibrosEditorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLibrosEditorialActionPerformed
        panelGraficas.fillData("libro", 7);
        panelGraficas.fillTit("editorial", 1, 2);
        panelGraficas.iniGraficaBarras("Libros por editorial");
    }//GEN-LAST:event_btnLibrosEditorialActionPerformed

    private void btnLibrosPAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLibrosPAutorActionPerformed
        panelGraficas.fillData("escribir", 2);
        panelGraficas.fillTit("autor", 1, 2);
        panelGraficas.iniGraficaBarras("Libros disponibles por autor");
    }//GEN-LAST:event_btnLibrosPAutorActionPerformed

    private void btnTipoEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTipoEmpleadosActionPerformed
        panelGraficas.fillData("empleado", 12);
        panelGraficas.iniGraficaPastel("Cantidad de empleados por tipo");
    }//GEN-LAST:event_btnTipoEmpleadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaGraficas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaGraficas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaGraficas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaGraficas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaGraficas dialog = new VentanaGraficas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLibrosEditorial;
    private javax.swing.JButton btnLibrosPAutor;
    private javax.swing.JButton btnLibrosVendidos;
    private javax.swing.JButton btnTipoEmpleados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private Modelo.graficasBDD panelGraficas;
    // End of variables declaration//GEN-END:variables
}
